export const data = [
  {
    id: "1",
    category: "cakes",
    title: "Tort wegański czekoladowy - 18 cm",
    price: 116,
    description: "",
  },
  {
    id: "2",
    category: "cakes",
    title: "Tort wegański czekoladowy - 23 cm",
    price: 176,
    description: "",
  },
  {
    id: "3",
    category: "cakes",
    title: "Tort bezowy z gorzką czekoladą, kremem marscapone i owocami - 23 cm",
    price: 96,
    description: "",
  },
  {
    id: "4",
    category: "cakes",
    title: "Easter Eggs - biszkopowe jajka przekładane kremem z białą czekoladą i lemon curdem",
    price: 12,
    description: "",
  },
  {
    id: "5",
    category: "cheesecakes",
    title: "Klasyczny (o smaku waniliowym) - 23 cm",
    price: 120,
    description: "",
  },
  {
    id: "6",
    category: "cheesecakes",
    title: "Kajmakowy / Carmel - 23 cm",
    price: 132,
    description: "",
  },
  {
    id: "7",
    category: "cheesecakes",
    title: "Z orzechami laskowymi / Hazelnut - 23 cm",
    price: 132,
    description: "",
  },
  {
    id: "8",
    category: "cheesecakes",
    title: "Z polewą truskawkową / Strawberry topping - 23 cm",
    price: 140,
    description: "",
  },
  {
    id: "9",
    category: "cookies",
    title: "Chocolate Chip Cookies",
    price: 3,
    description:
      "The classic American cookie, made with butter and Callebaut dark chocolate chips / Klasyczne, amerykańskie, maślane ciasteczko z kawałkami czekolady.",
  },
  {
    id: "10",
    category: "cookies",
    title: "Rougelach",
    price: 3,
    description:
      "A classic Jewish cookie, with a butter-cream cheese dough and a raisin-walnut cinnamon filling / Popularne żydowskie ciasteczka, zrobione z maślanego, kremowego ciasta, wypełnione nadzieniem z rodzynek i orzechów włoskich.",
  },
  {
    id: "11",
    category: "cookies",
    title: "Hamantashen",
    price: 3,
    description:
      "A traditional Jewish cookie for Purim, with an orange butter crust with a prune-apricot honey walnut filling. / Żydowskie ciasteczka, tradycyjnie wypiekane na Święto Purim, nazywane także Uszami Hamana. Nadzienie przygotowujemy z suszonych śliwek, moreli i miodu.",
  },
  {
    id: "12",
    category: "cookies",
    title: "Chocolate Crinkles",
    price: 3,
    description:
      "A traditional Christmas cookie, rich and thick with a soft fudgy brownie-like center. Lots of eggs, its definitely not vegan! / Tradycyjne, bożonarodzeniowe, lecz u nas dostępne na co dzień, ciasteczko czekoladowe z mięciutkim czekoladowym środkiem. Bardzo niewegańskie! ",
  },
  {
    id: "13",
    category: "cookies",
    title: "Lemon Ricotta Cookies",
    price: 3,
    description:
      "A rich soft cookie made with ricotta cheese, with lemon icing / Ciasteczka na bazie ricotty z lukrem cytrynowym o konsystencji chmurki :-)",
  },
  {
    id: "14",
    category: "cookies",
    title: "Peanut Butter Cookies",
    price: 3,
    description:
      "A crisp peanut butter cookie with chocolate cream filling! Inspired by the girl scout peanut butter cookies from my childhood :-) But with chocolate cream / Chrupiące ciasteczko z masłem orzechowym, przekładane kremem czekoladowym. Przywodzące wspomnienie z dzieciństwa - ciasteczek tradycyjnie sprzedawanych przez skautki :-)",
  },
  {
    id: "15",
    category: "bundt",
    title: "Cytrynowe z makiem / Lemon Poppy Seed",
    price: 72,
    description: "",
  },
  {
    id: "16",
    category: "bundt",
    title: "Karmelowo-owsiane / Oatmeal Carmel",
    price: 72,
    description: "",
  },
  {
    id: "17",
    category: "bundt",
    title: "Czekoladowe z polewą / Chocolate Sour Cream Bundt Cake with a Chocolate Glaze",
    price: 72,
    description: "",
  },
  {
    id: "18",
    category: "bundt",
    title: "Wegańskie cytrynowo-kokosowe / Vegan Lemon Coconut",
    price: 72,
    description: "",
  },
  {
    id: "19",
    category: "bundt",
    title: "Wegańskie pomarańczowe / Vegan Orange",
    price: 72,
    description: "",
  },
  {
    id: "20",
    category: "bread",
    title: "Chleb pszenno-żytni na zakwasie żytnim / Sourdough Rye",
    price: 10,
    description: "",
  },
  {
    id: "21",
    category: "bread",
    title: "Chleb pszenno-żytni z orzechami włoskimi / Walnut Rye",
    price: 8,
    description: "",
  },
  {
    id: "22",
    category: "bread",
    title: "Chałka / Challah",
    price: 10,
    description: "",
  },
  {
    id: "23",
    category: "bread",
    title: "Chleb 100% żytni / 100% Rye Bread",
    price: 10,
    description: "",
  },
  {
    id: "24",
    category: "bread",
    title: "Chleb pszenny z komosą ryżową / Quinoa Wheat",
    price: 10,
    description: "",
  },
  {
    id: "25",
    category: "bread",
    title: "Bagietka pszenna na zakwasie / Sourdough Baguette",
    price: 5,
    description: "",
  },
  {
    id: "26",
    category: "bread",
    title: "Wegańska sałatka jarzynowa (słoik 1l)",
    price: 25,
    description: "",
  },
  {
    id: "27",
    category: "spreads",
    title:
      "Smalec z białej fasoli z prażonym jabłkiem i cebulką / White Bean Spread with Baked Apples and Onions - 200g",
    price: 15,
    description: "",
  },
  {
    id: "28",
    category: "spreads",
    title: "Konfitura z czerwonej cebuli / Sweet Red Onion Spread- 200g",
    price: 15,
    description: "",
  },
  {
    id: "29",
    category: "spreads",
    title: "Sojonez z koperkiem / Vegan Mayonnaise with Dill - 200g",
    price: 15,
    description: "",
  },
  {
    id: "30",
    category: "spreads",
    title: "Pasta bezjajeczna / Vegan Egg Salad- 200g",
    price: 15,
    description: "",
  },
  {
    id: "31",
    category: "spreads",
    title: "Twarożek wegański z rzodkiewką / Vegan Cottage Cheese with radish - 200g",
    price: 15,
    description: "",
  },
  {
    id: "32",
    category: "spreads",
    title: "Wegański sos tatarski / Vegan Tartar Sauce - 200g",
    price: 15,
    description: "",
  },
  {
    id: "33",
    category: "pate",
    title:
      "Pasztet jaglany z grzybami i owocami jałowca / Millet Paté with Mushrooms and Juniper Berries - 15,5 x 6 cm",
    price: 19,
    description: "",
  },
  {
    id: "34",
    category: "pate",
    title: "Pasztet jaglany z grzybami i owocami jałowca / Millet Paté with Mushrooms and Juniper Berries - 20 x 9 cm",
    price: 28,
    description: "",
  },
  {
    id: "35",
    category: "pate",
    title: "Pasztet warzywny z ciecierzycą i koperkiem / Vegetable Paté with Chickpeas and Dill 15.5x6 cm",
    price: 19,
    description: "",
  },
  {
    id: "36",
    category: "pate",
    title: "Pasztet warzywny z ciecierzycą i koperkiem / Vegetable Paté with Chickpeas and Dill - 20 x 9 cm",
    price: 28,
    description: "",
  },
];
